INSERT INTO TOPICS (ID, TITLE, ATTACHEMENT) VALUES (1,'CHAOS', null);




INSERT INTO TEAM_MEMBER_DETAILS VALUES (1,'IS3987','VIGNESH','DEVELOPER','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (2,'IS3988','Naveen','manager','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (3,'IS3989','chandrasekar','DEVELOPER','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (4,'IS3999','VIGNESH','DEVELOPER','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (5,'IS3234','Naveen','manager','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (6,'IS3453','chandrasekar','DEVELOPER','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (7,'IS3233','VIGNESH','DEVELOPER','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (8,'IS3432','Naveen','manager','HDS','123',1);
INSERT INTO TEAM_MEMBER_DETAILS VALUES (9,'IS3435','chandrasekar','DEVELOPER','HDS','123',1);

INSERT INTO TECHTALK_TEAMS(ID, TEAM_NAME, TEAM_MEMBER_DETAILS_ID) VALUES (1,'UNSTOPPABLE',1);


--INSERT INTO SCOREBOARD VALUES (1,1,1,10,1);

