CREATE TABLE `TEAM_MEMBER_DETAILS` (
	`ID` INT NOT NULL,
	`EMPID` VARCHAR(255) NOT NULL UNIQUE,
	`EMPNAME` VARCHAR(255) NOT NULL,
	`DESIGNATION` VARCHAR(255) NOT NULL,
	`TEAM_NAME` VARCHAR(255) NOT NULL,
	`BU` VARCHAR(255) NOT NULL,
	`TOPIC_ID` INT,
	PRIMARY KEY (`ID`,`EMPID`)
);

CREATE TABLE `TECHTALK_TEAMS` (
	`ID` INT NOT NULL,
	`TEAM_NAME` VARCHAR(255) NOT NULL,
	`TEAM_MEMBER_DETAILS_ID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SCOREBOARD` (
	`ID` INT NOT NULL,
	`WEEK_NO` INT NOT NULL,
	`PRESENTER` INT NOT NULL,
	`SCORE` INT NOT NULL,
	`TOPIC_ID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TOPICS` (
	`ID` INT NOT NULL,
	`TITLE` varchar(255) NOT NULL,
	`ATTACHEMENT` blob,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `RATINGS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`FEED1` INT,
	`FEED2` INT,
	`FEED3` INT,
	`FEED4` INT,
	`FEED5` INT,
	`FEED6` INT,
	`TOPIC_ID` INT,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `TEAM_MEMBER_DETAILS` ADD CONSTRAINT `TEAM_MEMBER_DETAILS_fk0` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPICS`(`ID`);

ALTER TABLE `TECHTALK_TEAMS` ADD CONSTRAINT `TECHTALK_TEAMS_fk0` FOREIGN KEY (`TEAM_MEMBER_DETAILS_ID`) REFERENCES `TEAM_MEMBER_DETAILS`(`ID`);

ALTER TABLE `SCOREBOARD` ADD CONSTRAINT `SCOREBOARD_fk0` FOREIGN KEY (`PRESENTER`) REFERENCES `TEAM_MEMBER_DETAILS`(`ID`);

ALTER TABLE `SCOREBOARD` ADD CONSTRAINT `SCOREBOARD_fk1` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPICS`(`ID`);

ALTER TABLE `RATINGS` ADD CONSTRAINT `RATINGS_fk0` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPICS`(`ID`);
